/**
 * This model class represents Noun objects, which form the subject of a given question on a test.
 * This class is marked with the @Entity attribute, and will therefore be mirrored in the database, as the Noun TABLE
 */
package uk.ac.bangor.cs.cambria.AcademiGymraeg.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import uk.ac.bangor.cs.cambria.AcademiGymraeg.enums.Gender;

/**
 * @author ptg22svs, cnb22xdk, jcj23xfb
 */

@Entity
public class Noun {

	/**
	 * id attribute. The unique identifier for each Noun object, and the primary key
	 * for the Noun TABLE in the database. The value will be autogenerated, and
	 * cannot be updated once created.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(nullable = false, updatable = false)
	private Long nounId;

	/**
	 * welshNoun attribute. The Welsh language representation of the Noun.
	 */
	@Pattern(regexp = "^[\\p{L} '\\-]+$")
	@NotBlank
	@Column(nullable = false)
	private String welshNoun;

	/**
	 * englishNoun attribute. The English language representation of the Noun.
	 */
	@Pattern(regexp = "^[\\p{L} '\\-]+$")
	@NotBlank
	@Column(nullable = false)
	private String englishNoun;

	/**
	 * gender attribute. Represents the gender classification for the Welsh language
	 * representation of the noun. Attribute is of type "gender", which allows 3
	 * values: Masculine, Feminine and Plural
	 */
	@NotNull
	@Column(nullable = false)
	private Gender gender;

	public Noun(String englishNoun, String welshNoun, Gender gender) {
		this.englishNoun = englishNoun;
		this.welshNoun = welshNoun;
		this.gender = gender;
	}

	public Noun() {
	}

	
	public String getWelshNoun() {
		return welshNoun;
	}

	
	public void setWelshNoun(String welshNoun) {
		this.welshNoun = welshNoun;
	}

	
	public String getEnglishNoun() {
		return englishNoun;
	}

	
	public void setEnglishNoun(String englishNoun) {
		this.englishNoun = englishNoun;
	}

	
	public Gender getGender() {
		return gender;
	}

	
	public void setGender(Gender gender) {
		this.gender = gender;
	}

	public void setNounId(Long nounId) {
		this.nounId = nounId;
	}

	
	public Long getNounId() {
		return nounId;
	}

	@Override
	public String toString() {
		return this.welshNoun + " | " + this.englishNoun;
	}

}
